import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import Breadcrumbs from "@/components/Breadcrumbs";
// import { Preloader } from "@/components/ui/Preloader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`h-full`}>
      <body className="min-h-full">

        <div className="page">
          <Header />

          <main className="main">
            <Breadcrumbs />

            {children}
          </main>

          <Footer />
        </div>

      </body>
    </html>
  );
}
